### ISSUE TITLE
关于扩容耗时

### ISSUE THREAD

**Issue by LvBay** [youzan/nsq#116]
集群配置：1个nsqlookupd, 1个nsqadmin，3个nsqd

分区：1个order-topic，分区数为100，副本数为3

扩容时，新增一个nsqd-4。刚开始，nsqd-4没有任何分区副本。

接下来通过nsqadmin页面发现，每隔10分钟nsqd-4节点会新增一个分区副本

如果按上面的节奏，集群想要达到所有副本均衡分散在4个nsqd节点上，需要 100 分区* 3副本 / 4 nsqd * 10 分钟 = 750分钟。

请问为什么时间间隔要设置成10分钟？如果调小，可能会造成什么影响？
@absolute8511

**Comment by absolute8511** [comment]
是为了避免平衡太快, 影响在线服务.  可以考虑支持动态调整平衡间隔, 有兴趣的话欢迎提交pr支持这个功能

**Comment by LvBay** [comment]
https://github.com/youzan/nsq/blob/b64a24d36c590be923c038c7972acb0f532cf825/consistence/data_placement_mgr.go#L2287-L2289 这个地方是否可以改成阻塞模式，等待集群稳定再继续下面的循环，而不是直接return。
通过nsqlookup日志发现，外层的for循环实际上每次执行完第一个元素的任务就从这里结束了。

**Comment by LvBay** [comment]
如果要实现动态调整平衡间隔，可以根据哪些因素去调度？现在还没有思路～

**Comment by absolute8511** [comment]
主要需要考虑集群写入量和需要迁移的topic写入量就行了. 最简单的就是先提供一个API修改检查平衡的等待间隔. 高级点就是根据当前写入量自适应调整.

**Comment by LvBay** [comment]
懂了。麻烦再解答下上面那段代码的问题

**Comment by absolute8511** [comment]
等待集群稳定, 和等一会再检查, 效果上是差不多的.
