### ISSUE TITLE
多机房&多网卡监听配置

### ISSUE THREAD

**Issue by sukui** [youzan/nsq#12]
现在能支持多机房&多网卡监听配置么，现在有个应用场景. 除了服务器内网需要进行消息消费之外，外网还需要做一个channel 消费端来消费同步数据. 如果这样需要怎么配置服务？

**Comment by absolute8511** [comment]
暂不支持多网卡的绑定这种部署方式的. 建议nsq只提供内网服务, 再搞个proxy服务将数据透传到外网服务
