### ISSUE TITLE
select the least load factor node 

### ISSUE THREAD

**Issue by Damon07** [youzan/nsq#148]
https://github.com/youzan/nsq/blob/18884a6505fb6ab8cfe9d496f3d3e2081e26d201/consistence/data_placement_mgr.go#L1657

We should update the minLF, otherwise the last node will be selected ?

**Comment by absolute8511** [comment]
Yeah, you are right. Thanks for pointing it out and could you please give a pr on this and add some test case?

**Comment by Damon07** [comment]
ok, I will fix it later
