### ISSUE TITLE
关于延迟消息的一些疑问

### ISSUE THREAD

**Issue by x-wesley** [youzan/nsq#151]
官方的延迟消息是在生产端DPUB，
为什么有赞的延迟消息是在消费端REQ？

这么设计是为了什么呢？

**Comment by absolute8511** [comment]
因为我们发现官方的dpub不适合大规模使用, 所以没有采用. 这种属于延时任务的需求内部已经有其他产品满足了.

**Comment by x-wesley** [comment]
> 因为我们发现官方的dpub不适合大规模使用, 所以没有采用(后面如果有合适的支撑大规模的设计方案会考虑增加支持). 另外这种属于延时任务的需求内部已经有其他产品满足了.

这个延迟任务的产品有开源么？

**Comment by absolute8511** [comment]
这方面目前没有开源的计划
