### ISSUE TITLE
ectd配置问题

### ISSUE THREAD

**Issue by koalacxr** [youzan/nsq#17]
引用https://github.com/coreos/etcd 的环境，出现如下错误：

E1223 10:44:28.050456   98763 nsqd_node_etcd.go:258] consistence.(*NsqdEtcdMgr).WatchLookupdLeader watcher key[/NSQMetaData/message/NsqlookupdInfo/LookupdLeaderSession] error: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.
E1223 10:44:33.053676   98763 nsqd_node_etcd.go:258] consistence.(*NsqdEtcdMgr).WatchLookupdLeader watcher key[/NSQMetaData/message/NsqlookupdInfo/LookupdLeaderSession] error: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.

有关于ectd配置的文档吗？

**Comment by koalacxr** [comment]
etcd 用的是什么版本？

**Comment by absolute8511** [comment]
目前只支持V2 的api, 最新版本貌似移除了V2 api的支持, 所以需要用支持v2 api的etcd版本
