### ISSUE TITLE
请教关于NSQ Topic的问题

### ISSUE THREAD

**Issue by cychub** [youzan/nsq#177]
关于NSQ的topic
1. 当producer根据NSQLookup找到某个NSQD之后，会在这个NSQD上创建这个topic, 后续所有的相关的topic的消息，都会只发送到这个NSQD instance上?
2. 如果topic的消息都发送到某一个NSQD instance上，如果topic的消息数量很大，是否会有不平衡的问题？
3. 如果有不平衡的问题，如何解决？

**Comment by absolute8511** [comment]
有分区的概念, 一个topic可以有多个分区分布在多个节点

**Comment by cychub** [comment]
> 有分区的概念, 一个topic可以有多个分区分布在多个节点

如果只有一个partition是不是所有的消息只会落在一个节点上？

**Comment by absolute8511** [comment]
是的

**Comment by cychub** [comment]
@absolute8511  感谢，针对这个问题，如果只有一个分区，为了避免消息比较多的topic都落到同一个节点的情况发生，这种情况需要怎么处理？
我们现在的做法是这样的，不知道是否有什么问题，或者有更好的方法？
1. 在多个节点同时创建这个topic
2. 生产者在pub消息的时候，尽量均匀的往所有有这个topic的节点发布消息
感谢！

**Comment by absolute8511** [comment]
你创建多分区的topic就行了, sdk会自动处理的
