### ISSUE TITLE
Create Topic失败

### ISSUE THREAD

**Issue by koalacxr** [youzan/nsq#18]
Create Topic [https://github.com/youzan/nsq/blob/7f4429f4d9df7cd33c4ec4d58e73343c2b975763/doc/resources/ordered_topic_create.png](url)

按上述图片进行创建Topic不成功，没有错误提示，直接刷新了页面。
最后把最后一次操作的错误信息显示在界面上。

创建Topic除了启动nsqlookupd, nsqd, nsqadmin 外，还需要配置什么，比如：etcd要建什么目录，KV值之类的。

感谢～

**Comment by absolute8511** [comment]
创建参数是什么, 注意分区数*副本数不能大于nsqd节点数, 运维方面参考 , https://github.com/youzan/nsq/blob/master/doc/nsq-operation-reference.md

**Comment by loveowen** [comment]
I0616 19:22:15.782491   71942 data.go:698] clusterinfo.(*ClusterInfo).ListAllLookupdNodes CI: querying nsqlookupd http://127.0.0.1:4161/listlookup
I0616 19:22:15.782973   71942 data.go:358] clusterinfo.(*ClusterInfo).GetLookupdTopicProducers.func1 CI: querying nsqlookupd http://:/lookup?topic=test
I0616 19:22:15.783014   71942 http.go:1098] nsqadmin.(*httpServer).createTopicChannelHandler.func1 Failed to query any nsqlookupd: Get http:///lookup?topic=test: http: no Host in request URL

**Comment by loveowen** [comment]
@koalacxr 大哥，这种情况遇到过吗

**Comment by loveowen** [comment]
启动参数 ./bin/nsqadmin --lookupd-http-address=127.0.0.1:4161
