### ISSUE TITLE
在Nodes上创建Topic

### ISSUE THREAD

**Issue by koalacxr** [youzan/nsq#19]
问题1: 在Nodes界面显示两个Node，端口分别4161和5161。在Lookup界面显示 127.0.0.1:4161 (configured) 和 127.0.0.1:4161 (Leader)，没有127.0.0.1:5161信息。

问题2: 同时开启两个Node，端口分别4161和5161，创建Topic不能选择创建在哪个Node上，只能默认创建在4161上；关闭4161端口，再创建Topic，就在5161上创建了。

问题3: 在Nodes界面显示两个Node，端口分别4161和5161，这两个Node之间什么关系，会同步数据吗？

**Comment by absolute8511** [comment]
你说的Node是nsqlookup还是nsqd, 你可以先看看重构后的一些文档, 整理一下节点的关系, 以及分区和副本的概念

**Comment by koalacxr** [comment]
nsqd的

**Comment by koalacxr** [comment]
Node是nsqd 的

**Comment by absolute8511** [comment]
Lookup界面显示的只有nsqlookup, topic创建在哪个nsqd节点是由nsqlookup来自动分配的. 数据同步如果是多副本的会自动同步数据.
