### ISSUE TITLE
有序的Topic，Producer调用Publish异常

### ISSUE THREAD

**Issue by koalacxr** [youzan/nsq#21]
使用go-nsq，producer_test.go中TestProducerConnection测试：

当Topic是有序时(order), Producer调用Publish异常：
producer_test.go:114: should lazily connect - E_BAD_PARTITION topic partition is not valid for multi partition: -1

**Comment by koalacxr** [comment]
在producer.go文件中，增加如下可以正常调用：
func (w *Producer) PublishWithPart(topic string, part string, body []byte) error {
	_, err := w.sendCommand(PublishWithPart(topic, part, body))
	return err
}

是不是producer.go还没有完善？

**Comment by absolute8511** [comment]
请参考文档中顺序topic的例子: https://github.com/youzan/nsq/blob/master/doc/Advanced-usage-reference.md

**Comment by koalacxr** [comment]
👌
