### ISSUE TITLE
 build failed on Windows - miss getDelayQueueDBName Method in dqname_windows.go

### ISSUE THREAD

**Issue by wenxiongwang** [youzan/nsq#23]
github.com\youzan\nsq\nsqd\dqname_windows.go
github.com\youzan\nsq\nsqd\delay_queue.go

verssion: nsq-0.3.7-HA.1.6.4, delay_queue.go used getDelayQueueDBName method.

**Comment by absolute8511** [comment]
之前没有做windows的兼容性测试, 这个我们稍后修复一下, 然后打个包. 你们可以测试下
