### ISSUE TITLE
创建topic时Retention Days 设置为0，不起作用么

### ISSUE THREAD

**Issue by tyutlt** [youzan/nsq#46]
创建topic时Retention Days 设置为0，老的数据不会被删除，持续累积导致硬盘刷满。
配置文件里设置retention_size_per_day 不起作用吗？设置成1个G，然后还是会刷满硬盘

**Comment by absolute8511** [comment]
被消费了吗, 如果没有消费的数据是不会清理的. 如果是0, 会使用nsqd服务端的配置 `retention_days`

**Comment by tyutlt** [comment]
被消费了，nsqd配置文件里设置retention_days ，启动会报参数已经配置，采用默认的配置。我这边在topic上设置了retention_days时间

**Comment by tyutlt** [comment]
可以加个微信细聊下吗

**Comment by absolute8511** [comment]
可以, 帐号就是github账号名
