### ISSUE TITLE
failed to find lookupd leader at this moment

### ISSUE THREAD

**Issue by MrsZ** [youzan/nsq#50]
http.go:1282] nsqadmin.(*httpServer).clusterStatsHandler WARNING: failed to find lookupd leader at this moment
我没有部署集群，就单台的启动了nsq，无法在页面添加topic，看log里面显示这个错误。有啥解决办法吗？没有部署etcd

**Comment by absolute8511** [comment]
需要启动nsqlookup节点

**Comment by MrsZ** [comment]
lookupd  nsqd  nsqadmin
