### ISSUE TITLE
notifyLeaderChanged load topic info failed: Key not found

### ISSUE THREAD

**Issue by MrsZ** [youzan/nsq#51]
./nsqlookupd -config=/opt/nsq/youzan/bin/nsqlookupd.cfg

E0705 10:03:01.227648   11365 nsqlookup_coordinator.go:267] consistence.(*NsqLookupCoordinator).notifyLeaderChanged load topic info failed: Key not found

![image](https://user-images.githubusercontent.com/13742821/42298902-edb5bca0-803a-11e8-864d-86e6cd6a7d1a.png)

**Comment by absolute8511** [comment]
是不是没创建任何topic? 可以忽略, 创建一个topic就好了

**Comment by MrsZ** [comment]
创建topic正常 谢谢
