### ISSUE TITLE
关于文档

### ISSUE THREAD

**Issue by yy-chen** [youzan/nsq#58]
https://github.com/youzan/nsq/blob/master/doc/how-we-redesign-the-nsq-smart-client.md

大佬们这个有中文版的么

**Comment by absolute8511** [comment]
@DoraALin 看看整理下

**Comment by DoraALin** [comment]
https://github.com/youzan/nsq/blob/doc/nsq_client_cn/doc/how-we-redesign-the-nsq-smart-client-cn.md 修改完成后合并。
