### ISSUE TITLE
NSQ集群节点机器配置

### ISSUE THREAD

**Issue by Enrique8191** [youzan/nsq#6]
求一份集群机器配置清单

**Comment by absolute8511** [comment]
默认配置可以参考 contrib目录下的

**Comment by Enrique8191** [comment]
@absolute8511 sorrym 可能是我没表达清楚。 我是想要一份诸如内存，CPU, 硬盘， 网卡，生产部署实例个数的硬件配置手册

**Comment by Enrique8191** [comment]
@absolute8511 sorry,  可能是我没表达清楚。 我是想要一份诸如内存，CPU, 硬盘， 网卡，生产部署实例个数的硬件配置说明

**Comment by absolute8511** [comment]
集群配置可能需要根据业务的需求来配置, 建议配置5台 8核8GB, 千兆网卡, 1TB磁盘的机器即可. 可以根据业务发展情况随时平滑扩容缩容的
