### ISSUE TITLE
About topics' authentication mechanism

### ISSUE THREAD

**Issue by pfctgeorge** [youzan/nsq#69]
I have read the docs and found that there is not any reference about auth mechanism of the topics in cluster. So, my question is that how we can do to allow multiple tenants to use a same cluster, and how   a tenant can do to protect the topics from bad effects of any read/write operation from an another tenant.

**Comment by absolute8511** [comment]
We use the same auth mechanism with the original NSQ, so you can both use the tls or use the `-auth-http-address`. More docs can be found here: https://nsq.io/components/nsqd.html

**Comment by pfctgeorge** [comment]
Oh, I see that and it really helps. One more question, if I set the `auth_secret` in the config of a Go client, will the auth mechanism of pub/sub operations work, just like a single nsqd server?

**Comment by absolute8511** [comment]
Yes, it should work as the same.

**Comment by pfctgeorge** [comment]
Thanks a lot.
