### ISSUE TITLE
请教一个问题：topic  创建在哪个nsqd node上，nsqlookup是怎么分配的？相关源码大概在哪个文件里？

### ISSUE THREAD

**Issue by qingfengming** [youzan/nsq#79]
如题，创建topic时，  创建在哪个nsqd node上，nsqlookup是怎么分配的？相关源码大概在哪个文件里？

是不是lookup 扔数据到 etcd里， nsqd 拉下来后 更具数据new 一个 topic？

**Comment by absolute8511** [comment]
参考这里 : https://github.com/youzan/nsq/blob/master/consistence/data_placement_mgr.go

**Comment by qingfengming** [comment]
> 参考这里 : https://github.com/youzan/nsq/blob/master/consistence/data_placement_mgr.go

多谢，还有一个问题： 假设一个三副本的topic，一个副本的 nsqd node 挂了， 这时候这个topic 会到另一个nsqd 节点拉起来一个新的副本。   它是怎么选择哪个nsqd node 作为新的副本位置的？这部分相关源码在哪？ 找了挺久找不到。希望有空了解答下，非常感谢。
