### ISSUE TITLE
any doc about nodeid?

### ISSUE THREAD

**Issue by elvizlai** [youzan/nsq#98]
For doc: 

https://github.com/youzan/nsq/blob/master/doc/nsq-operation-reference.md#%E9%9B%86%E7%BE%A4%E8%8A%82%E7%82%B9%E7%BB%B4%E6%8A%A4

I tried: `curl http://NSQ_ADMIN:4171/api/nodes`, but no nodeid found.

also tried: `curl http://NSQ_LOOKUPD:4161/nodes`

Or please update the doc.

**Comment by absolute8511** [comment]
Sure, the doc has been updated.

**Comment by elvizlai** [comment]
@absolute8511 Thanks, found it.

Another question: Can deleted node add back? Using some API or just restart nsqd?

**Comment by absolute8511** [comment]
Restart will be enough

**Comment by elvizlai** [comment]
@absolute8511 whoops, rejoined node has no topic, is there any strategy to rebalance?

**Comment by absolute8511** [comment]
Should be balanced automatically if the balance is enabled.
